### ISSUE TITLE
Map doesn't change

### ISSUE THREAD

**Issue by SwaggerMcSwaggy** [yovanoc/cookietouch#64]
Sometimes the map doesn't change. The bot then waits for a few minutes until an Error comes back.
This issue occurs mostly combined with fight: true.

**Comment by yovanoc** [comment]
Can you explain a little more, please? The exact error and/or some screens would be appreciated, thanks

**Comment by yovanoc** [comment]
I can't see for now. This project is stopped until the end of June, so I let your issue opened, and I come back to you at this moment, sorry for this delay

**Comment by SwaggerMcSwaggy** [comment]
You shouldn't be sorry for any delay. You are the developer. Without you, nothing would be going forward.
And for that, I wanna thank you.

**Comment by yovanoc** [comment]
Thanks for this nice message. I apologize because I was planning the first release for the first of April and I had a personal incident who made this project stopped for a little bit, but as soon as I can get myself back into this, believe me, this will be a beautiful project ahah

**Comment by yovanoc** [comment]
@SwaggerMcSwaggy I fixed the problem, but it will be available for the next push, so in less than a month I think now :)
